# Generated by Django 3.2.4 on 2021-06-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(help_text='Enter the institute name', max_length=30)),
                ('start_year', models.IntegerField(help_text='Enter the course starting year', max_length=4)),
                ('end_year', models.IntegerField(help_text='Enter the course ending year', max_length=4)),
                ('score', models.FloatField(help_text='Enter your score, here for instance 9.8')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='Enter the project name here', max_length=30)),
                ('project_desc', models.TextField(help_text='Enter the project description here')),
                ('project_stack', models.CharField(help_text='Enter programming languages here', max_length=20)),
            ],
        ),
    ]
