# Generated by Django 3.2.4 on 2021-06-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_url',
            field=models.URLField(default='Link to the project', help_text='Link to the project if any'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='institute_name',
            field=models.CharField(help_text='Enter the institute name', max_length=50),
        ),
    ]
