# Generated by Django 3.2.4 on 2021-06-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20210620_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='degree_type',
            field=models.CharField(default='degree', help_text='Program of study', max_length=50),
            preserve_default=False,
        ),
    ]
